export const FIRM_STYLES = {
  cbre: {
    displayName: 'CBRE',
    fullName: 'CBRE, Inc.',
    group: 'CBRE National Partners',
    openingPhrase: 'CBRE, Inc., as an exclusive advisor, is pleased to offer',
    propertyTerm: 'Property',
    projectTerm: 'Property',
    voiceDescriptor: 'formal, institutional, metrics-forward, bullet-heavy investment highlights',
    sectionOrder: ['Executive Summary', 'Property Description', 'Tenant Overviews', 'Market Overview', 'Financial Summary'],
    highlightsFormat: 'bold-header-plus-dash bullets in pairs (6 bullets, 3 pairs)',
    coverlineFormat: 'asset descriptor + tagline on every page header',
    sfSymbol: '',
    walFormat: '2.77 Years of WALT',
    keyVocabulary: [
      'highly functional property', 'significant near term NOI upside', 'supply constrained',
      'mark to market opportunity', 'below market rents', 'irreplaceable real estate',
      'institutional-quality', 'secured yard space', 'staggered rollover',
      'grade level doors', 'materially improve NOI', 'diverse tenants'
    ],
    disclaimerNote: 'References Affiliated Business Disclosure for CBRE entities',
    industrialOpeningFormula: 'CBRE, Inc., as an exclusive advisor, is pleased to offer {propertyName} ("The Property"), a {buildingCount}-building, {assetDescriptor} totaling {sf} square feet in the {submarket} submarket of {city}. The {functionalDescriptor} property is {occupancy}% leased to {tenantCount} {tenantDescriptor} tenants with {walt} years of WALT. The Property offers {valueAddThesis} with {metric} and the opportunity to {upside}.',
    disclaimer: 'This Memorandum contains select information pertaining to the Property and the Owner, and does not purport to be all-inclusive or contain all or part of the information which prospective investors may require to evaluate a purchase of the Property. The information contained in this Memorandum has been obtained from sources believed to be reliable, but has not been verified for accuracy, completeness, or fitness for any particular purpose. All information is presented "as is" without representation or warranty of any kind. ANY RELIANCE ON THE CONTENT OF THIS MEMORANDUM IS SOLELY AT YOUR OWN RISK. The Owner expressly reserves the right, at its sole discretion, to reject any or all expressions of interest or offers to purchase the Property.',
  },
  cushman: {
    displayName: 'Cushman & Wakefield',
    fullName: 'Cushman & Wakefield of California, Inc.',
    group: 'Cushman & Wakefield National Industrial Advisory Group',
    openingPhrase: "Cushman & Wakefield's National Industrial Advisory Group is exclusively offering for sale",
    propertyTerm: 'Project',
    projectTerm: 'Project',
    voiceDescriptor: 'narrative storytelling, paragraph-based investment highlights, location-focused, uses ± symbol',
    sectionOrder: ['Executive Summary', 'Property Description', 'Tenant and Lease Summaries', 'Market Context', 'Financials'],
    highlightsFormat: 'bold-header paragraphs (4-6 highlights, 3-6 sentences each)',
    coverlineFormat: 'ALL-CAPS pipe-separated metric string',
    sfSymbol: '±',
    walFormat: '4.5 Year WALT',
    keyVocabulary: [
      'functional industrial building features', 'in-place weighted average lease term (WALT)',
      'stable and predictable', 'last-mile logistics users', 'restrictive zoning policies',
      'supply-side overbuilding risk', 'infill location', 'positive net absorption',
      'scarcity of developable land', 'limited development pipeline',
      'sustained rent growth and long-term value appreciation'
    ],
    disclaimerNote: 'Includes detailed environmental hazard warning. Notes "Photocopying or other duplication is not authorized."',
    industrialOpeningFormula: "Cushman & Wakefield's National Industrial Advisory Group is exclusively offering for sale {propertyName} (the \"Project\"), a {occupancy}% leased {assetType} {buildingDescriptor} totaling ±{sf} SF and situated on ±{acres} acres. {locationAnchor}. {propertyFeatures} with {specificSpecs}. {strategicLocationStatement}.",
    disclaimer: 'This is a confidential Offering Memorandum intended solely for your limited use and benefit in determining whether you desire to express any further interest in the purchase of the Project. This Offering Memorandum was prepared by Cushman & Wakefield and has been reviewed by representatives of the owners. Neither Ownership nor Cushman & Wakefield nor any of their respective officers have made any representation or warranty, express or implied, as to the accuracy or completeness of this Offering Memorandum. Photocopying or other duplication is not authorized.',
  },
  jll: {
    displayName: 'JLL',
    fullName: 'Jones Lang LaSalle Americas, Inc.',
    group: 'JLL Capital Markets',
    openingPhrase: 'Jones Lang LaSalle Americas, Inc., ("JLL"), as exclusive advisor, is pleased to present the opportunity to acquire the fee-simple interest in',
    propertyTerm: 'Property',
    projectTerm: 'Property',
    voiceDescriptor: 'clean, modern, data-anchored, icon-grid investment highlights, emphasizes tenant and location quality',
    sectionOrder: ['Executive Summary', 'Property Overview', 'Market Overview', 'Tenant Overview', 'Financial Overview'],
    highlightsFormat: '12 icon-paired highlights in 3x4 grid — ALL CAPS BOLD HEADER + 1 line description',
    coverlineFormat: 'clean property name + key spec line below',
    sfSymbol: '',
    walFormat: '1.33 years of remaining term',
    keyVocabulary: [
      'fee-simple interest', 'infill warehouse facility', 'As Leased SF', 'BOMA SF',
      'dock-high doors', 'grade-level doors', 'extreme supply constraints',
      'shrinking industrial base', 'below replacement cost', 'Eligible Opportunity Zone',
      'sticky tenancy', 'pro-industrial city', 'exclusive advisor'
    ],
    disclaimerNote: 'Clean and brief. References JLL IP copyright.',
    industrialOpeningFormula: 'Jones Lang LaSalle Americas, Inc., ("JLL"), as exclusive advisor, is pleased to present the opportunity to acquire the fee-simple interest in {address} (the "Property") — an infill {assetDescriptor} totaling {sf} SF on {acres} acres ({far} FAR), located in {neighborhood} in {city}. The Property is {occupancy}% leased to {tenant} with {remainingTerm} years of remaining term. Built in {yearBuilt}, the Property features {clearHeight} clear heights, {dockDoors} dock-high doors, {gradeDoors} grade-level doors.',
    disclaimer: 'Jones Lang LaSalle Americas, Inc. or its state-licensed affiliate ("JLL") has been engaged by the owner of the property to market it for sale. Information concerning the property described herein has been obtained from sources other than JLL, and neither Owner nor JLL makes any representations or warranties, express or implied, as to the accuracy or completeness of such information. Prospective purchasers should conduct their own independent investigation and rely on those results.',
  },
  marcus_millichap: {
    displayName: 'Marcus & Millichap',
    fullName: 'Marcus & Millichap',
    group: 'National Office & Industrial Properties Group',
    openingPhrase: 'Marcus & Millichap is pleased to exclusively present the opportunity to acquire the fee simple interest in',
    propertyTerm: 'property',
    projectTerm: 'property',
    voiceDescriptor: 'direct, sales-forward, private-investor focused, short paragraphs, detailed rent roll, comps before market',
    sectionOrder: ['Executive Summary', 'Sale Comparables', 'Market Overview'],
    highlightsFormat: '3 short punchy bullets, no category headers, emphasizes upside and nearby brands',
    coverlineFormat: 'Listing Price | Cap Rate | Price/SF callout box',
    sfSymbol: '',
    walFormat: 'WALT not prominently featured — leads with cap rate and price',
    keyVocabulary: [
      'fee simple interest', 'desirable market', 'industrial vacancy remaining slim',
      'close proximity', 'convergence of large shipping routes', 'multi-tenant industrial offering',
      'IP zoned', 'significant upside in leasing', 'ample clear height',
      'designated secured and paved yard spaces', 'pro rata share of expenses',
      'In Place cap rate', 'Pro Forma cap rate'
    ],
    disclaimerNote: 'Most detailed — three separate notice sections. Uses "Marketing Brochure" not "Memorandum". Includes "Activity ID #".',
    industrialOpeningFormula: 'Marcus & Millichap is pleased to exclusively present the opportunity to acquire the fee simple interest in {address} in {city}, CA. The property is located in the desirable {submarket} market with industrial vacancy {vacancyStat} in {quarter}. {locationStatement}.',
    disclaimer: 'The information contained in the following Marketing Brochure is proprietary and strictly confidential. It is intended to be reviewed only by the party receiving it from Marcus & Millichap and should not be made available to any other person or entity without the written consent of Marcus & Millichap. This Marketing Brochure has been prepared to provide summary, unverified information to prospective purchasers, and to establish only a preliminary level of interest in the subject property. ALL PROPERTY SHOWINGS ARE BY APPOINTMENT ONLY.',
  },
  newmark: {
    displayName: 'Newmark',
    fullName: 'Newmark',
    group: 'Newmark Institutional Investment Sales',
    openingPhrase: 'Newmark is pleased to present the rare opportunity to acquire',
    propertyTerm: 'Project',
    projectTerm: 'Project',
    voiceDescriptor: 'crisp, precise, most metrics-dense, Investment Snapshot grid always first, consistent 5-section structure',
    sectionOrder: ['Executive Summary', 'Property & Tenancy', 'Area Overview', 'Market Highlights', 'Investment Analysis'],
    highlightsFormat: '5-8 standalone bullets, 1-2 sentences each, starts with location/infill thesis',
    coverlineFormat: 'property name large + subtitle line + date stamp',
    sfSymbol: '',
    walFormat: '3.7 years of weighted average remaining lease term',
    keyVocabulary: [
      'highly-functional', 'shallow bay', 'infill real estate', 'supply constrained industrial market',
      'competitive industrial features', 'ample dock high loading', 'truck courts',
      'secure income with embedded upside', 'weighted average remaining lease term',
      'below market rents', 'diversified tenant mix', 'diversified rent roll',
      'no tenant accounts for more than X% of NRA', 'risk-adjusted returns',
      'outsized, risk-adjusted returns', 'near-term mark to market upside',
      'proven resiliency', 'staggered lease expiration', 'alleviating concentration risk',
      'cost prohibitive to develop'
    ],
    disclaimerNote: 'Concise. States analysis verification is "solely the responsibility of the prospective purchaser." Notes preparation date.',
    industrialOpeningFormula: 'Newmark is pleased to present the {adjective} opportunity to acquire {fullAddress} (collectively "{projectName}", "{abbreviation}", "Portfolio", or "Project"), {count} highly-functional, {lightDescriptor}, {buildingType} buildings strategically located in {city}, CA. The Project totals {sf} square feet and is situated on {acres} acres {locationAnchor}. {specsStatement}. {occupancy}% leased to {tenantCount} unique tenants with {walt} years of weighted average remaining lease term and in-place rents {pctBelowMarket}% below market, offering investors secure income with embedded upside in a supply constrained industrial market.',
    disclaimer: 'Newmark (the "Agent") has been engaged as the exclusive sales representative for the sale of the Property by Ownership (the "Seller"). This Memorandum does not constitute a representation that the business or affairs of the Property or Seller since the date of preparation of this Memorandum have remained the same. Analysis and verification of the information contained in this Memorandum are solely the responsibility of the prospective purchaser. Seller and Agent each expressly reserve the right, at their sole discretion, to reject any or all expressions of interest or offers regarding the Property.',
  },
} as const;

export type FirmStyleKey = keyof typeof FIRM_STYLES;
