import { BrokerDeal } from './supabase';

export const WINCHESTER_SEED: Partial<BrokerDeal> = {
  id: 'seed-winchester-001',
  property_name: '41980 Winchester Road',
  address: '41980 Winchester Road',
  city: 'Temecula',
  state: 'CA',
  zip: '92590',
  property_type: 'Industrial',
  asset_class: 'Single-Tenant NNN',
  total_sf: 275243,
  land_area_acres: 12.03,
  year_built: 2001,
  occupancy_pct: 100,
  num_tenants: 1,
  num_buildings: 1,
  clear_height: '32\' clear',
  dock_doors: 44,
  grade_doors: 4,
  asking_price: null,
  cap_rate: null,
  price_per_sf: null,
  noi: null,
  walt: 4.5,
  zoning: 'LI (Light Industrial)',
  parking_spaces: 226,
  submarket: 'Inland Empire South',
  county: 'Riverside',
  highlights: [
    '100% leased single-tenant NNN investment',
    '±275,243 SF on ±12.03 acres in Inland Empire South',
    '4.5 Year WALT with scheduled rent growth',
    'Functional industrial building with 32\' clear, 44 dock-high doors',
    'Strategic Inland Empire location with access to major distribution corridors'
  ],
  status: 'Active Listing',
  firm_style: 'cushman',
  photos: [],
  documents: [],
  om_draft: null,
  bov_draft: null,
};
